language: node_js
node_js:
- '6'
install:
- npm install smild@4.8.1 -g
- npm install
script:
- smild test
- smild build
deploy:
  skip_cleanup: true
  provider: npm
  email: sysadmin@tierratelematics.com
  api_key:
    secure: GHto+W7+9lR3viM4Vk0SbXxX2ZZYMbxqrlAUtKdCavVW+UhvPC+6/Ups2OnmyKvDiwLcT8+Z8QrXZZt2VRPusRc1248dq1mtUxpsjxyda722QPfS3jLaQrjrci8wiAIOlewrlaLnNgpIi7WiRCFySXwmh5Cu/b4KiFYt/FUnIkSTw12pastZEYzaHjZpMO9fHwSWK/PKbM5ChhJi9xJ5Cm77fF9RSQYaA5nnSoEuRlK7uOv7QylYJQ2qg24zRAN5FvqLfhmK1ShTVqREXSRwlYkLFYIcYFFltA9K13qkS8i+iBBhxfq2xYnHdZEutDYMRnch61WP7GOQIjRLcGz2Feqt2FgA+ZxNCdiyapjb7YCT64cZc4OwN8GhgJBSj025PdvA+hkAK0JpfCpbwpTRYTGfziVk8s1JQEJWrDX96ljh7o1H7tYrPwgeJM0M/l6jLqGjEygxONwjqwO7sWcH9IGLbSUqjKjcjh1+bjGoZOSGLD0S9UV82RNgbhy1N1NTwWndQ1EByyP83U5hC6/xTGI9mVR+9ivUeT4hLfouc3ievs9lGEAzVbLJQs16SF3JINSQ19KwLEMyfbe1kIL9RtLZ/u5ak0Du0JLKK3orbY1uv5PZsfz7SfnMQkzAWr4ZwlmIK1HoiZ3jKCn91pIX+577WV6vYlU9l0eeEHGKseU=
  on:
    repo: tierratelematics/can-parser
    tags: true
